
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Gets the root path of a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the path to check
 * 
 * # Returns
 * 
 * * `Result<GetRepositoryRootOutput, AppError>` - The root path and ID, or an error
 */
async getRepositoryRoot(input: GetRepositoryRootInput) : Promise<Result<GetRepositoryRootOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository_root", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new repository entry in the database.
 * This should only be called when a user explicitly adds a repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the repository path
 * * `db` - Database state for persisting repository data
 * 
 * # Returns
 * 
 * * `Result<CreateRepositoryOutput, AppError>` - Repository information or an error
 */
async createRepository(input: CreateRepositoryInput) : Promise<Result<CreateRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scans the filesystem for git repositories so the user can add many at once
 * instead of picking each folder by hand.
 * 
 * With no `roots`, the user's home directory is scanned. Scanning runs on the
 * blocking thread pool since large trees can take a moment to walk.
 * 
 * # Arguments
 * 
 * * `app` - App handle used to resolve the home directory
 * * `input` - Optional scan roots and depth
 * 
 * # Returns
 * 
 * * `Result<DiscoverRepositoriesOutput, AppError>` - Discovered repositories
 * and the roots that were scanned, or an error
 */
async discoverRepositories(input: DiscoverRepositoriesInput) : Promise<Result<DiscoverRepositoriesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_repositories", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets information about a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the repository ID
 * * `db` - Database state for persisting repository data
 * 
 * # Returns
 * 
 * * `Result<GetRepositoryOutput, AppError>` - Repository information or an error
 */
async getRepository(input: GetRepositoryInput) : Promise<Result<GetRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all repositories from the database.
 * 
 * # Arguments
 * 
 * * `db` - Database state for retrieving repositories
 * 
 * # Returns
 * 
 * * `Result<Vec<crate::shared::infrastructure::db::models::Repository>, AppError>` - List of repositories or an error
 */
async getRepositoryList() : Promise<Result<Repository[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a repository from the database.
 * 
 * # Arguments
 * 
 * * `db` - Database state for repository deletion
 * * `input` - Input parameters containing the repository ID
 * 
 * # Returns
 * 
 * * `Result<DeleteRepositoryOutput, AppError>` - Success status or an error
 */
async deleteRepository(input: DeleteRepositoryInput) : Promise<Result<DeleteRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cheap read-only check comparing git's current ref fingerprint against the
 * stored `last_sync_timestamp`. The frontend calls this on window focus for the
 * active repo to detect changes the watcher missed and heal silently.
 */
async getRepositorySyncStatus(input: GetRepositorySyncStatusInput) : Promise<Result<GetRepositorySyncStatusOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository_sync_status", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets branches from the database for a repository with optional filtering.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repo_id and optional filters
 * 
 * # Returns
 * 
 * * `Result<GetBranchListOutput, AppError>` - The list of branches or an error
 */
async getBranchList(input: GetBranchListInput) : Promise<Result<GetBranchListOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_list", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the current branch in a git repository (switches to another branch).
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and branch name
 * 
 * # Returns
 * 
 * * `Result<UpdateCurrentBranchOutput, AppError>` - The new current branch name or an error
 */
async updateCurrentBranch(input: UpdateCurrentBranchInput) : Promise<Result<UpdateCurrentBranchOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_current_branch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple branches from a git repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state for soft-deleting branches
 * * `input` - Input parameters containing path and branch names to delete
 * 
 * # Returns
 * 
 * * `Result<BatchDeleteBranchesOutput, AppError>` - The deleted branches or an error
 */
async batchDeleteBranches(input: BatchDeleteBranchesInput) : Promise<Result<BatchDeleteBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the reachability status of a commit SHA in a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and commit SHA
 * 
 * # Returns
 * 
 * * `Result<GetCommitReachabilityOutput, AppError>` - The reachability status or an error
 */
async getCommitReachability(input: GetCommitReachabilityInput) : Promise<Result<GetCommitReachabilityOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_reachability", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the merge status of a branch in a git repository.
 * Checks if the specified branch is fully merged into HEAD.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and branch name
 * 
 * # Returns
 * 
 * * `Result<GetBranchMergeStatusOutput, AppError>` - The merge status or an error
 */
async getBranchMergeStatus(input: GetBranchMergeStatusInput) : Promise<Result<GetBranchMergeStatusOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_merge_status", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the line-level diff stats of a branch in a git repository: lines
 * added/removed relative to the branch's merge-base with HEAD.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and branch name
 * 
 * # Returns
 * 
 * * `Result<GetBranchDiffStatsOutput, AppError>` - The diff stats or an error
 */
async getBranchDiffStats(input: GetBranchDiffStatsInput) : Promise<Result<GetBranchDiffStatsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_diff_stats", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets merge status and diff stats for a batch of branches in one call,
 * served from the persistent `(HEAD sha, branch sha)` cache with only the
 * misses computed (in parallel). Branches that fail to resolve are omitted
 * from the output rather than failing the batch.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and branch names
 * 
 * # Returns
 * 
 * * `Result<BulkGetBranchMetricsOutput, AppError>` - Metrics per resolved branch or an error
 */
async bulkGetBranchMetrics(input: BulkGetBranchMetricsInput) : Promise<Result<BulkGetBranchMetricsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_get_branch_metrics", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a restoration of a deleted branch in a git repository.
 * 
 * # Arguments
 * 
 * * `app` - The AppHandle
 * * `db` - Database state for updating branch status
 * * `input` - Input parameters containing path and branch info
 * 
 * # Returns
 * 
 * * `Result<CreateBranchRestorationOutput, AppError>` - The restoration result or an error
 */
async createBranchRestoration(input: CreateBranchRestorationInput) : Promise<Result<CreateBranchRestorationOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch_restoration", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates restorations of multiple deleted branches in a git repository.
 * 
 * # Arguments
 * 
 * * `app` - The AppHandle
 * * `db` - Database state for updating branch status
 * * `input` - Input parameters containing path and branch infos
 * 
 * # Returns
 * 
 * * `Result<BatchCreateBranchRestorationsOutput, AppError>` - The restoration results or an error
 */
async batchCreateBranchRestorations(input: BatchCreateBranchRestorationsInput) : Promise<Result<BatchCreateBranchRestorationsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_create_branch_restorations", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Walks history across all local branches (+ HEAD) and returns one page of
 * commits with parent edges and ref decorations.
 */
async listCommitHistory(input: ListCommitHistoryInput) : Promise<Result<ListCommitHistoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_commit_history", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Locates a commit in the history walk and returns a window around it —
 * used for deep-linking (`?commit=<sha>`) and the hover graph preview.
 */
async getCommitHistoryWindow(input: GetCommitHistoryWindowInput) : Promise<Result<GetCommitHistoryWindowOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_history_window", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the newest commits reachable from one branch tip. Scoped to that
 * branch's ancestry — unlike `list_commit_history`, which walks every local
 * branch at once.
 */
async listBranchCommits(input: ListBranchCommitsInput) : Promise<Result<ListBranchCommitsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branch_commits", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Computes ahead/behind vs the base for the requested local branches. A
 * branch with `ahead == 0` is fully contained in base (safe to delete).
 */
async listBranchComparison(input: ListBranchComparisonInput) : Promise<Result<ListBranchComparisonOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branch_comparison", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists every file changed by a branch (vs merge-base with HEAD) or a
 * commit (vs its first parent), with per-file line stats.
 */
async listChangedFiles(input: ListChangedFilesInput) : Promise<Result<ListChangedFilesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_changed_files", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The full textual diff (hunks with old/new line numbers) of one file
 * changed by the target.
 */
async getFileDiff(input: GetFileDiffInput) : Promise<Result<GetFileDiffOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a line range of a file as it exists on the diff's target side —
 * used by the diff view to expand the hidden context between hunks.
 */
async getFileLines(input: GetFileLinesInput) : Promise<Result<GetFileLinesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_lines", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Analyzes the code structure of a diff: which symbols each changed file's
 * hunks touch, and which changed files import each other — the data behind
 * the canvas view and the list view's impact badges.
 */
async getDiffStructure(input: GetDiffStructureInput) : Promise<Result<GetDiffStructureOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diff_structure", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Explains a single changed file: builds its unified diff, runs the agent,
 * streams `ExplanationChunkEvent`s, and returns the full text.
 */
async createFileExplanation(input: CreateFileExplanationInput) : Promise<Result<CreateFileExplanationOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_file_explanation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Explains a changed file one hunk at a time: the agent echoes a `@@HUNK n@@`
 * marker before each explanation, so the streamed text splits back into
 * per-hunk sections. Files with no textual hunks (binary, pure rename) return
 * immediately without running the agent.
 */
async createHunkExplanation(input: CreateHunkExplanationInput) : Promise<Result<CreateHunkExplanationOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_hunk_explanation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Explains every changed file (or a named subset) one at a time — agents are
 * effectively single-session, so files run sequentially rather than in
 * parallel. Per file it streams chunks under the `batchId`, emits a
 * completion event, and bumps batch progress. A single file's failure does
 * not abort the batch (its completion event carries `error`).
 */
async createDiffExplanationBatch(input: CreateDiffExplanationBatchInput) : Promise<Result<CreateDiffExplanationBatchOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_diff_explanation_batch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancels an in-flight single or batch explanation by its id.
 */
async cancelExplanation(input: CancelExplanationInput) : Promise<Result<CancelExplanationOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_explanation", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all selected branches for a repository (active branches only).
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<ListBranchSelectionOutput, AppError>` - The selected branches or an error
 */
async listBranchSelection(input: ListBranchSelectionInput) : Promise<Result<ListBranchSelectionOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branch_selection", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all selected deleted branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<ListDeletedBranchSelectionOutput, AppError>` - The selected deleted branches or an error
 */
async listDeletedBranchSelection(input: ListDeletedBranchSelectionInput) : Promise<Result<ListDeletedBranchSelectionOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_deleted_branch_selection", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates selection status for specific branches.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID, branch names, and selection status
 * 
 * # Returns
 * 
 * * `Result<UpdateBranchSelectionBatchOutput, AppError>` - Success or an error
 */
async updateBranchSelectionBatch(input: UpdateBranchSelectionBatchInput) : Promise<Result<UpdateBranchSelectionBatchOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_branch_selection_batch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sets all branches to selected/unselected based on deletion status filter.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID, selection status, deletion status filter, and exclusion flags
 * 
 * # Returns
 * 
 * * `Result<SetBranchSelectionAllOutput, AppError>` - Success or an error
 */
async setBranchSelectionAll(input: SetBranchSelectionAllInput) : Promise<Result<SetBranchSelectionAllOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_branch_selection_all", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<ListLockedBranchesOutput, AppError>` - The locked branches or an error
 */
async listLockedBranches(input: ListLockedBranchesInput) : Promise<Result<ListLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates multiple locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchCreateLockedBranchesOutput, AppError>` - Success or an error
 */
async batchCreateLockedBranches(input: BatchCreateLockedBranchesInput) : Promise<Result<BatchCreateLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_create_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchDeleteLockedBranchesOutput, AppError>` - Success or an error
 */
async batchDeleteLockedBranches(input: BatchDeleteLockedBranchesInput) : Promise<Result<BatchDeleteLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes all locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<DeleteAllLockedBranchesOutput, AppError>` - Success or an error
 */
async deleteAllLockedBranches(input: DeleteAllLockedBranchesInput) : Promise<Result<DeleteAllLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_all_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scans a single repository for cleanable folders and measures each one.
 * Sizing large trees can take a moment, so it runs on the blocking pool and
 * streams throttled `CleanupScanProgressEvent`s.
 */
async scanCleanupTargets(input: ScanCleanupTargetsInput) : Promise<Result<ScanCleanupTargetsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_cleanup_targets", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists stale registered repositories with their reclaimable `.gitignore`d
 * folders. The DB read is quick and done up front; the per-repo filesystem
 * walk runs on the blocking pool with throttled progress events.
 */
async listStaleRepositories(input: ListStaleRepositoriesInput) : Promise<Result<ListStaleRepositoriesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stale_repositories", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the requested folders after re-validating each against the
 * repository root and its `.gitignore` stack. A failure on one target is
 * reported per-target and does not abort the rest.
 */
async cleanRepository(input: CleanRepositoryInput) : Promise<Result<CleanRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clean_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists every worktree of the repository (the main worktree first, then each
 * linked worktree with its branch, HEAD, and lock status).
 */
async listWorktrees(input: ListWorktreesInput) : Promise<Result<ListWorktreesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_worktrees", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a worktree and returns its resolved metadata.
 */
async addWorktree(input: AddWorktreeInput) : Promise<Result<AddWorktreeOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_worktree", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes the requested worktree (deleting its working tree and pruning its
 * admin files). The main worktree cannot be removed.
 */
async removeWorktree(input: RemoveWorktreeInput) : Promise<Result<RemoveWorktreeOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_worktree", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Locks a worktree so it can't be pruned.
 */
async lockWorktree(input: LockWorktreeInput) : Promise<Result<LockWorktreeOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lock_worktree", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlocks a previously locked worktree.
 */
async unlockWorktree(input: UnlockWorktreeInput) : Promise<Result<UnlockWorktreeOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_worktree", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
branchDeleted: BranchDeletedEvent,
branchRestored: BranchRestoredEvent,
branchSwitched: BranchSwitchedEvent,
cleanupScanProgress: CleanupScanProgressEvent,
cleanupTargetCleaned: CleanupTargetCleanedEvent,
explanationBatchProgress: ExplanationBatchProgressEvent,
explanationChunk: ExplanationChunkEvent,
explanationFileCompleted: ExplanationFileCompletedEvent,
notification: NotificationEvent,
repositoryChanged: RepositoryChangedEvent,
repositoryLoaded: RepositoryLoadedEvent,
repositoryScanProgress: RepositoryScanProgressEvent,
staleScanProgress: StaleScanProgressEvent
}>({
branchDeleted: "branch-deleted",
branchRestored: "branch-restored",
branchSwitched: "branch-switched",
cleanupScanProgress: "cleanup-scan-progress",
cleanupTargetCleaned: "cleanup-target-cleaned",
explanationBatchProgress: "explanation-batch-progress",
explanationChunk: "explanation-chunk",
explanationFileCompleted: "explanation-file-completed",
notification: "notification",
repositoryChanged: "repository-changed",
repositoryLoaded: "repository-loaded",
repositoryScanProgress: "repository-scan-progress",
staleScanProgress: "stale-scan-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type AddWorktreeInput = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string; 
/**
 * Administrative name for the new worktree.
 */
name: string; 
/**
 * Absolute path where the new worktree should be checked out. Must not exist yet.
 */
worktreePath: string; 
/**
 * Local branch to check out. When omitted, git creates a new branch named `name`.
 */
reference: string | null; 
/**
 * Lock the worktree immediately after creating it.
 */
lock: boolean | null }
export type AddWorktreeOutput = { worktree: Worktree }
export type AppError = { message: string; kind: string; description: string | null }
export type BatchCreateBranchRestorationsInput = { path: string; repoId: string; branchInfos: DeletedBranch[] }
export type BatchCreateBranchRestorationsOutput = { results: RestoreBranchResult[] }
export type BatchCreateLockedBranchesInput = { repoId: string; branchNames: string[] }
export type BatchCreateLockedBranchesOutput = Record<string, never>
export type BatchDeleteBranchesInput = { path: string; repoId: string; branches: string[] }
export type BatchDeleteBranchesOutput = { deletedBranches: DeletedBranchInfo[] }
export type BatchDeleteLockedBranchesInput = { repoId: string; branchNames: string[] }
export type BatchDeleteLockedBranchesOutput = Record<string, never>
export type Branch = { name: string; fullyMerged: boolean; lastCommit: Commit; current: boolean; 
/**
 * Remote tracking ref this branch follows (e.g. `origin/main`); `None`
 * when the branch has no upstream configured.
 */
upstream: string | null; deletedAt: string | null; isReachable: boolean | null; isSelected: boolean; isLocked: boolean }
/**
 * How a local branch stands relative to the base — the cleanup signals.
 * `ahead == 0` means the branch is fully contained in base (safe to delete).
 */
export type BranchComparison = { name: string; sha: string; 
/**
 * Commits on this branch not in base (unique work — lost if deleted).
 */
ahead: number; 
/**
 * Commits in base not on this branch.
 */
behind: number }
export type BranchDeletedEvent = { deletedBranches: DeletedBranchInfo[]; repositoryPath: string }
/**
 * Comprehensive filter configuration for querying branches
 */
export type BranchFilters = { 
/**
 * Filter by deletion status (default: Active - only non-deleted branches)
 */
deletionStatus?: DeletionStatusFilter; 
/**
 * Filter by merge status (default: All)
 */
mergeStatus?: MergeStatusFilter; 
/**
 * Filter by selection status (default: All)
 */
selectionStatus?: SelectionStatusFilter; 
/**
 * Filter by lock status (default: All)
 */
lockStatus?: LockStatusFilter; 
/**
 * Whether to include the current branch in results (default: true)
 */
includeCurrent?: boolean }
export type BranchMetrics = { name: string; isMerged: boolean; linesAdded: number; linesRemoved: number }
export type BranchRestoredEvent = { restoredBranch: Branch; repositoryPath: string }
export type BranchSwitchedEvent = { fromBranch: string; toBranch: string; repositoryPath: string }
export type BulkGetBranchMetricsInput = { path: string; branchNames: string[] }
export type BulkGetBranchMetricsOutput = { metrics: BranchMetrics[] }
export type CancelExplanationInput = { 
/**
 * The `requestId` or `batchId` to cancel.
 */
id: string }
export type CancelExplanationOutput = { 
/**
 * Whether a matching in-flight explanation was found and signalled.
 */
cancelled: boolean }
/**
 * One entry in the changed-files list.
 */
export type ChangedFile = { 
/**
 * Path in the target tree (old path for deleted files).
 */
path: string; 
/**
 * Previous path, present only for renames.
 */
oldPath: string | null; status: FileChangeStatus; linesAdded: number; linesRemoved: number; isBinary: boolean }
/**
 * A definition whose line range intersects the file's changed lines.
 * 
 * Note on deletions: a pure-deletion hunk is attributed to the new-side line
 * where the deletion happened, so a deletion exactly at a symbol boundary
 * may credit the neighboring symbol — acceptable for a review summary.
 */
export type ChangedSymbol = { name: string; kind: SymbolKind; 
/**
 * 1-based line of the definition on the diff's target side.
 */
startLine: number; endLine: number }
export type CleanRepositoryInput = { 
/**
 * Repository id (used for the audit log).
 */
repositoryId: string; 
/**
 * Absolute path to the repository's working directory.
 */
repositoryPath: string; 
/**
 * Absolute paths of the folders to delete.
 */
targets: string[]; 
/**
 * Trash (recoverable) or permanent deletion.
 */
mode: DeletionMode }
export type CleanRepositoryOutput = { 
/**
 * Total bytes freed across the successful targets.
 */
freedBytes: number; results: TargetResult[] }
/**
 * Emitted while `scan_cleanup_targets` measures a repository's cleanable
 * folders (one repo, per-target sizing).
 */
export type CleanupScanProgressEvent = { 
/**
 * Number of targets measured so far.
 */
measured: number; 
/**
 * Path currently being measured.
 */
currentPath: string | null }
/**
 * A single cleanable directory and its measured size. Every target is
 * discovered from the repository's `.gitignore` stack.
 */
export type CleanupTarget = { 
/**
 * Absolute path to the directory.
 */
path: string; 
/**
 * The directory's own name (last path component), e.g. `node_modules`.
 */
folderName: string; 
/**
 * Total size on disk in bytes.
 */
sizeBytes: number }
/**
 * Emitted once per folder successfully deleted by `clean_repository`, so the
 * frontend can optimistically drop it from cached scan results without waiting
 * for a full re-scan.
 */
export type CleanupTargetCleanedEvent = { 
/**
 * Id of the repository the folder belonged to.
 */
repositoryId: string; 
/**
 * Absolute path of the deleted folder.
 */
path: string; 
/**
 * Bytes reclaimed by deleting it.
 */
bytesFreed: number }
export type Commit = { sha: string; shortSha: string; date: string; 
/**
 * Full commit message (subject + body).
 */
message: string; 
/**
 * First line of the message (the subject), for compact display.
 */
summary: string; author: string; email: string }
export type ConflictDetails = { originalName: string; conflictingName: string }
export type ConflictResolution = "Overwrite" | "Rename" | "Skip"
export type CreateBranchRestorationInput = { path: string; repoId: string; branchInfo: DeletedBranch }
export type CreateBranchRestorationOutput = { result: RestoreBranchResult }
export type CreateDiffExplanationBatchInput = { 
/**
 * Caller-chosen id used to correlate every file's stream and to cancel.
 */
batchId: string; path: string; branchName?: string | null; commitSha?: string | null; 
/**
 * Files to explain; when omitted the full changed set is derived.
 */
filePaths?: string[] | null; 
/**
 * Reviewer-chosen explanation shape; defaults to succinct.
 */
style?: ExplanationStyle; 
/**
 * Whole-file summary vs per-change (inline) explanations; defaults to file.
 */
detail?: ExplanationDetail }
export type CreateDiffExplanationBatchOutput = { batchId: string; 
/**
 * Number of files processed (completed or failed).
 */
total: number }
export type CreateFileExplanationInput = { 
/**
 * Caller-chosen id used to correlate streamed chunks and to cancel.
 */
requestId: string; 
/**
 * Filesystem path to the repository.
 */
path: string; branchName?: string | null; commitSha?: string | null; 
/**
 * Path of the file to explain (as returned by `list_changed_files`).
 */
filePath: string; 
/**
 * Rename source path — pass `ChangedFile.old_path` through for renames.
 */
oldPath?: string | null; 
/**
 * Reviewer-chosen explanation shape; defaults to succinct.
 */
style?: ExplanationStyle }
export type CreateFileExplanationOutput = { requestId: string; filePath: string; 
/**
 * The full accumulated explanation text.
 */
text: string }
export type CreateHunkExplanationInput = { 
/**
 * Caller-chosen id used to correlate streamed chunks and to cancel.
 */
requestId: string; path: string; branchName?: string | null; commitSha?: string | null; filePath: string; oldPath?: string | null; style?: ExplanationStyle }
export type CreateHunkExplanationOutput = { requestId: string; filePath: string; 
/**
 * The full marker-delimited text (`@@HUNK n@@` + explanation per hunk).
 */
text: string; 
/**
 * The git header of each hunk, in order — labels the parsed sections.
 */
hunkHeaders: string[] }
export type CreateRepositoryInput = { path: string }
export type CreateRepositoryOutput = { path: string; branches: Branch[]; currentBranch: string; branchesCount: number; name: string; id: string }
export type DeleteAllLockedBranchesInput = { repoId: string }
export type DeleteAllLockedBranchesOutput = Record<string, never>
export type DeleteRepositoryInput = { id: string }
export type DeleteRepositoryOutput = { success: boolean }
export type DeletedBranch = { originalName: string; targetName: string; commitSha: string; conflictResolution: ConflictResolution | null }
export type DeletedBranchInfo = { branch: Branch; rawOutput: string }
/**
 * Deletion strategy chosen per cleanup action.
 */
export type DeletionMode = 
/**
 * Move to the OS recycle bin — recoverable by the user (default).
 */
"trash" | 
/**
 * Permanent `remove_dir_all` — irreversible, space reclaimed immediately.
 */
"permanent"
/**
 * Filter for branch deletion status
 */
export type DeletionStatusFilter = 
/**
 * Only active (non-deleted) branches
 */
"active" | 
/**
 * Only deleted branches
 */
"deleted" | 
/**
 * Both active and deleted branches
 */
"all"
/**
 * A contiguous region of change with surrounding context lines.
 */
export type DiffHunk = { 
/**
 * The `@@ -a,b +c,d @@ …` header as git prints it.
 */
header: string; oldStart: number; oldLines: number; newStart: number; newLines: number; lines: DiffLine[] }
/**
 * One line inside a hunk. Content excludes the trailing newline and the
 * leading origin marker.
 */
export type DiffLine = { kind: DiffLineKind; content: string; 
/**
 * Line number in the base tree; `None` for added lines.
 */
oldLineNo: number | null; 
/**
 * Line number in the target tree; `None` for removed lines.
 */
newLineNo: number | null }
/**
 * The role of a single diff line.
 */
export type DiffLineKind = "context" | "added" | "removed"
export type DiscoverRepositoriesInput = { 
/**
 * Directories to scan. When empty, the user's home directory is scanned.
 */
roots?: string[]; 
/**
 * Maximum depth to descend below each root. Defaults to `DEFAULT_MAX_DEPTH`.
 */
maxDepth?: number | null; 
/**
 * Include linked git worktrees in the results. Off by default: a linked
 * worktree shares its repository with the main worktree, so it isn't a
 * standalone repo. Enable to register worktrees and manage their branches.
 */
includeWorktrees?: boolean }
export type DiscoverRepositoriesOutput = { 
/**
 * Git repositories found under the scanned roots.
 */
repositories: DiscoveredRepository[]; 
/**
 * The roots that were actually scanned (resolved home directory when the
 * caller passed no explicit roots).
 */
scannedRoots: string[]; 
/**
 * Total number of directories visited during the walk. Reported so the UI
 * can show a truthful final count even when the scan was too fast for the
 * throttled progress events to keep up.
 */
scannedDirs: number }
export type DiscoveredRepository = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string; 
/**
 * Folder name, used as the default display name.
 */
name: string; 
/**
 * True for a linked git worktree (only present when the scan opted in).
 */
isWorktree: boolean; 
/**
 * For a linked worktree, the working directory of its main repository.
 */
mainRepositoryPath: string | null }
/**
 * Emitted after each file in a batch is processed, so the UI can show
 * `done / total` progress.
 */
export type ExplanationBatchProgressEvent = { batchId: string; 
/**
 * Files processed so far (completed or failed).
 */
done: number; 
/**
 * Total files in the batch.
 */
total: number }
/**
 * One incremental slice of an explanation's text. Deltas are coalesced on a
 * light timer before emission, so this fires a handful of times per file
 * rather than once per token.
 */
export type ExplanationChunkEvent = { 
/**
 * Correlation id (single: `requestId`; batch: `batchId`).
 */
requestId: string; 
/**
 * Path of the file this delta explains.
 */
filePath: string; 
/**
 * Text produced since the previous chunk.
 */
delta: string }
/**
 * Whether an explanation covers the whole file (one summary) or each change
 * group (inline per-hunk). Mirrors the frontend's up-front "Detail" choice;
 * carried by the batch command so "Explain all" runs the intended mode.
 */
export type ExplanationDetail = 
/**
 * One explanation for the whole file.
 */
"file" | 
/**
 * One explanation per change group (hunk).
 */
"hunks"
/**
 * Emitted once a file's explanation finishes (success or per-file failure) —
 * only used by the batch flow, where the command return value can't carry
 * per-file results. `error` is set instead of `text` when that file failed.
 */
export type ExplanationFileCompletedEvent = { 
/**
 * Correlation id (the `batchId`).
 */
requestId: string; filePath: string; 
/**
 * Full accumulated explanation; empty when `error` is set.
 */
text: string; 
/**
 * Present when this file's explanation failed; the batch continues.
 */
error: string | null }
/**
 * The reviewer-chosen shape of an explanation. Chosen per request (a header
 * selector in the UI); the default keeps explanations short.
 */
export type ExplanationStyle = 
/**
 * One or two sentences: what changed and why it matters.
 */
"succinct" | 
/**
 * A fuller walkthrough of the change and its notable specifics.
 */
"detailed" | 
/**
 * Reviewer lens: risks, likely bugs, and edge cases to double-check.
 */
"reviewFocused" | 
/**
 * Non-technical summary for PMs/QAs — no jargon.
 */
"plainLanguage"
/**
 * What happened to a file between the two trees.
 */
export type FileChangeStatus = "added" | "deleted" | "modified" | "renamed"
/**
 * One import found in a changed file.
 */
export type FileImport = { 
/**
 * The specifier as written: `./foo`, `$ui/x`, `react`.
 */
specifier: string; 
/**
 * Repo-relative path this import resolves to — set only when the target
 * is another CHANGED file (v1 scope); packages and unchanged files stay
 * `None`.
 */
resolvedPath: string | null }
/**
 * The analyzed structure of one changed file.
 */
export type FileStructure = { 
/**
 * Path in the target tree (old path for deleted files).
 */
path: string; language: StructureLanguage; 
/**
 * False for unknown languages, deleted/binary files, oversized blobs,
 * and parse failures — all non-fatal.
 */
parsed: boolean; changedSymbols: ChangedSymbol[]; imports: FileImport[] }
export type GetBranchDiffStatsInput = { path: string; branchName: string }
export type GetBranchDiffStatsOutput = { linesAdded: number; linesRemoved: number }
export type GetBranchListInput = { repoId: string; filters?: BranchFilters }
export type GetBranchListOutput = { branches: Branch[] }
export type GetBranchMergeStatusInput = { path: string; branchName: string }
export type GetBranchMergeStatusOutput = { isMerged: boolean }
export type GetCommitHistoryWindowInput = { path: string; 
/**
 * Full or short SHA of the commit to locate.
 */
targetSha: string; 
/**
 * How many commits of context to include before (newer than) the target.
 */
contextBefore?: number; 
/**
 * Window size (clamped to 1..=500); always spans through the target.
 */
limit: number }
export type GetCommitHistoryWindowOutput = { commits: HistoryCommit[]; 
/**
 * Absolute index (in the full walk) of `commits[0]`.
 */
startIndex: number; 
/**
 * Absolute index of the target commit.
 */
targetIndex: number; 
/**
 * Cursor to continue paging after this window; `null` at the end.
 */
nextCursor: string | null; totalCount: number }
export type GetCommitReachabilityInput = { path: string; commitSha: string }
export type GetCommitReachabilityOutput = { isReachable: boolean }
export type GetDiffStructureInput = { 
/**
 * Filesystem path to the repository.
 */
path: string; 
/**
 * Analyze a branch (vs merge-base with HEAD). Mutually exclusive with
 * `commit_sha`.
 */
branchName?: string | null; 
/**
 * Analyze a commit (vs its first parent). Mutually exclusive with
 * `branch_name`.
 */
commitSha?: string | null }
export type GetDiffStructureOutput = { 
/**
 * One entry per changed file, in diff order.
 */
files: FileStructure[]; 
/**
 * Import relations between changed files, deduped and sorted.
 */
edges: StructureEdge[] }
export type GetFileDiffInput = { path: string; 
/**
 * See [`ListChangedFilesInput::branch_name`].
 */
branchName?: string | null; 
/**
 * See [`ListChangedFilesInput::commit_sha`].
 */
commitSha?: string | null; 
/**
 * Path of the file in the target tree (as returned by `list_changed_files`).
 */
filePath: string; 
/**
 * Rename source path — pass `ChangedFile.old_path` through so rename
 * detection can pair both sides.
 */
oldPath?: string | null }
export type GetFileDiffOutput = { path: string; oldPath: string | null; status: FileChangeStatus; 
/**
 * Binary files carry no hunks.
 */
isBinary: boolean; 
/**
 * True when the diff exceeded the per-file line cap and was cut short.
 */
truncated: boolean; hunks: DiffHunk[] }
export type GetFileLinesInput = { path: string; 
/**
 * See [`ListChangedFilesInput::branch_name`].
 */
branchName?: string | null; 
/**
 * See [`ListChangedFilesInput::commit_sha`].
 */
commitSha?: string | null; 
/**
 * Path of the file on the diff's target side.
 */
filePath: string; 
/**
 * First line of the range, 1-based inclusive.
 */
startLine: number; 
/**
 * Last line of the range, inclusive. `0` means "through end of file".
 */
endLine: number }
export type GetFileLinesOutput = { 
/**
 * The requested lines (trailing newlines stripped). Empty for binary
 * files or ranges past the end of the file.
 */
lines: string[]; 
/**
 * Total number of lines in the file on the target side.
 */
totalLines: number }
export type GetRepositoryInput = { id: string }
export type GetRepositoryOutput = { path: string; branches: Branch[]; currentBranch: string; branchesCount: number; name: string; id: string; lastSyncedAt: string | null; 
/**
 * Whether this repository is a linked git worktree (not the main worktree).
 */
isWorktree: boolean }
export type GetRepositoryRootInput = { path: string }
export type GetRepositoryRootOutput = { rootPath: string; id: string | null }
export type GetRepositorySyncStatusInput = { repositoryId: string }
export type GetRepositorySyncStatusOutput = { 
/**
 * True when git's on-disk state no longer matches the last synced
 * fingerprint — i.e. the DB projection has drifted (a change the watcher
 * may have missed, e.g. while the app was backgrounded).
 */
drifted: boolean }
/**
 * A single commit in the history walk, with the topology the graph needs.
 */
export type HistoryCommit = { sha: string; shortSha: string; 
/**
 * Parent SHAs, first-parent first. Empty for the root commit; >1 for merges.
 */
parents: string[]; 
/**
 * Branch/tag/remote names pointing at this commit, local branches first.
 */
refs: RefDecoration[]; author: string; email: string; date: string; message: string }
export type ListBranchCommitsInput = { path: string; 
/**
 * Local branch whose ancestry to walk.
 */
branch: string; 
/**
 * How many commits to return, newest first (clamped to 1..=500).
 */
limit: number }
export type ListBranchCommitsOutput = { 
/**
 * Newest first, carrying the full message (subject + body).
 */
commits: HistoryCommit[]; 
/**
 * Whether the branch has commits older than the returned window.
 */
hasMore: boolean }
export type ListBranchComparisonInput = { path: string; 
/**
 * Base branch to compare against; defaults to main/master, else HEAD.
 * An explicit base that doesn't exist is an error.
 */
base?: string | null; 
/**
 * Local branches to compute; names that no longer exist are skipped
 * silently (absence in the result is NOT `ahead == 0`).
 */
branchNames: string[] }
export type ListBranchComparisonOutput = { baseName: string; baseSha: string; branches: BranchComparison[] }
export type ListBranchSelectionInput = { repoId: string }
export type ListBranchSelectionOutput = { branches: string[] }
export type ListChangedFilesInput = { 
/**
 * Filesystem path to the repository (frontend resolves this from the repo id).
 */
path: string; 
/**
 * Diff a branch against its merge-base with HEAD. Mutually exclusive
 * with `commit_sha`.
 */
branchName?: string | null; 
/**
 * Diff a commit against its first parent. Mutually exclusive with
 * `branch_name`.
 */
commitSha?: string | null }
export type ListChangedFilesOutput = { files: ChangedFile[]; 
/**
 * Sum of per-file added lines.
 */
linesAdded: number; 
/**
 * Sum of per-file removed lines.
 */
linesRemoved: number }
export type ListCommitHistoryInput = { 
/**
 * Filesystem path to the repository (frontend resolves this from the repo id).
 */
path: string; 
/**
 * Opaque cursor from the previous page; omit for the first page.
 */
cursor?: string | null; 
/**
 * Window size — how many commits to return (clamped to 1..=500).
 */
limit: number }
export type ListCommitHistoryOutput = { commits: HistoryCommit[]; 
/**
 * Cursor for the next page; `null` on the last page.
 */
nextCursor: string | null; 
/**
 * Exact total number of commits in the walk.
 */
totalCount: number }
export type ListDeletedBranchSelectionInput = { repoId: string }
export type ListDeletedBranchSelectionOutput = { branches: string[] }
export type ListLockedBranchesInput = { repoId: string }
export type ListLockedBranchesOutput = { branches: string[] }
export type ListStaleRepositoriesInput = { 
/**
 * A repository is stale when its most recent activity is older than this.
 */
thresholdDays?: number | null }
export type ListStaleRepositoriesOutput = { repositories: StaleRepository[]; 
/**
 * Total reclaimable bytes across all stale repositories.
 */
totalReclaimableBytes: number }
export type ListWorktreesInput = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string }
export type ListWorktreesOutput = { worktrees: Worktree[] }
/**
 * Filter for branch lock status
 */
export type LockStatusFilter = 
/**
 * Only locked branches
 */
"locked" | 
/**
 * Only unlocked branches
 */
"unlocked" | 
/**
 * Both locked and unlocked branches
 */
"all"
export type LockWorktreeInput = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string; 
/**
 * Administrative name of the worktree to lock.
 */
name: string; 
/**
 * Optional reason recorded with the lock.
 */
reason: string | null }
export type LockWorktreeOutput = { name: string }
/**
 * Filter for branch merge status
 */
export type MergeStatusFilter = 
/**
 * Only fully merged branches
 */
"merged" | 
/**
 * Only unmerged branches
 */
"unmerged" | 
/**
 * Both merged and unmerged branches
 */
"all"
export type NotificationEvent = { title: string; message: string; kind: NotificationKind; duration: number | null }
export type NotificationKind = "Success" | "Error" | "Warning" | "Info"
export type RefDecoration = { name: string; kind: RefKind }
/**
 * What kind of ref points at a commit — so the UI can emphasise local branch
 * heads (the comparison unit) over tags and remotes.
 */
export type RefKind = "localBranch" | "remoteBranch" | "tag"
export type RemoveWorktreeInput = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string; 
/**
 * Administrative name of the worktree to remove.
 */
name: string; 
/**
 * Remove even if the worktree is locked.
 */
force: boolean | null }
export type RemoveWorktreeOutput = { 
/**
 * Name of the worktree that was removed.
 */
name: string }
export type Repository = { id: string; name: string; path: string; currentBranch: string; branchesCount: number; createdAt: string; updatedAt: string; lastSyncTimestamp: number | null; lastSyncedAt: string | null }
/**
 * Emitted when the filesystem watcher detects an external change to a watched
 * repository and has re-synced it to the database. The frontend listens for
 * this and invalidates the affected TanStack queries.
 */
export type RepositoryChangedEvent = { repositoryId: string }
export type RepositoryLoadedEvent = { repositoryPath: string; repositoryName: string; branchesCount: number }
/**
 * Emitted periodically while `discover_repositories` walks the filesystem so
 * the UI can show live scan progress (folders visited, repositories found so
 * far). Throttled by the command to avoid flooding the event channel.
 */
export type RepositoryScanProgressEvent = { scannedDirs: number; foundCount: number; currentPath: string | null }
export type RestoreBranchResult = { success: boolean; branchName: string; message: string; requiresUserAction: boolean; conflictDetails: ConflictDetails | null; skipped: boolean; branch: Branch | null }
export type ScanCleanupTargetsInput = { 
/**
 * Absolute path to the repository's working directory.
 */
repositoryPath: string }
export type ScanCleanupTargetsOutput = { targets: CleanupTarget[]; 
/**
 * Sum of all target sizes in bytes.
 */
totalBytes: number }
/**
 * Filter for branch selection status
 */
export type SelectionStatusFilter = 
/**
 * Only selected branches
 */
"selected" | 
/**
 * Only unselected branches
 */
"unselected" | 
/**
 * Both selected and unselected branches
 */
"all"
export type SetBranchSelectionAllInput = { repoId: string; isSelected: boolean; deletionStatus: DeletionStatusFilter; excludeLocked?: boolean; excludeCurrent?: boolean }
export type SetBranchSelectionAllOutput = Record<string, never>
export type StaleRepository = { id: string; name: string; path: string; 
/**
 * Unix seconds of the repository's most recent activity.
 */
staleSince: number; reclaimableBytes: number; targets: CleanupTarget[] }
/**
 * Emitted while `list_stale_repositories` walks the registered repositories.
 */
export type StaleScanProgressEvent = { 
/**
 * Repositories examined so far.
 */
scanned: number; 
/**
 * Total repositories to examine.
 */
total: number; 
/**
 * Stale repositories with reclaimable space found so far.
 */
found: number; 
/**
 * Name of the repository currently being examined.
 */
currentName: string | null }
/**
 * A directed relation between two changed files (`from` imports `to`).
 * 
 * At most one edge exists per `(from, to)` pair: when the source file uses
 * any of the symbols it imports from the target, the edge is upgraded to
 * `Call` and `symbols` lists what is used; otherwise it stays `Import`.
 */
export type StructureEdge = { from: string; to: string; kind: StructureEdgeKind; 
/**
 * For `Call` edges: the sorted, deduped symbol names the source file
 * uses from the target. Empty for plain `Import` edges.
 */
symbols: string[] }
/**
 * The relation an edge represents.
 */
export type StructureEdgeKind = "import" | 
/**
 * The source file imports AND uses at least one symbol from the target.
 */
"call"
/**
 * The grammar used to parse a changed file.
 */
export type StructureLanguage = "typescript" | "javascript" | "svelte" | 
/**
 * Anything without a supported grammar — the file still appears as a
 * node, just with no parsed internals.
 */
"unknown"
/**
 * What kind of definition a changed symbol is.
 */
export type SymbolKind = "function" | "method" | "class" | 
/**
 * A Svelte component (synthetic whole-file symbol).
 */
"component"
export type TargetResult = { path: string; ok: boolean; bytesFreed: number; error: string | null }
export type UnlockWorktreeInput = { 
/**
 * Absolute path to the repository's working directory.
 */
path: string; 
/**
 * Administrative name of the worktree to unlock.
 */
name: string }
export type UnlockWorktreeOutput = { name: string }
export type UpdateBranchSelectionBatchInput = { repoId: string; branchNames: string[]; isSelected: boolean }
export type UpdateBranchSelectionBatchOutput = Record<string, never>
export type UpdateCurrentBranchInput = { path: string; branch: string }
export type UpdateCurrentBranchOutput = { currentBranch: string }
export type Worktree = { 
/**
 * Administrative name (the entry under `.git/worktrees/`). For the main
 * worktree this is a synthesized name derived from its directory.
 */
name: string; 
/**
 * Absolute path to the worktree's working directory.
 */
path: string; 
/**
 * Short name of the checked-out branch, or `None` when detached or missing.
 */
branch: string | null; 
/**
 * SHA of the worktree's `HEAD`, or `None` when it can't be resolved.
 */
headSha: string | null; 
/**
 * Whether the worktree is locked (protected from pruning).
 */
isLocked: boolean; 
/**
 * Optional reason recorded when the worktree was locked.
 */
lockReason: string | null; 
/**
 * The main worktree (the repository's own working directory). It can't be
 * removed or locked, so the UI hides those actions for it.
 */
isMain: boolean; 
/**
 * Whether git considers this worktree prunable (its working directory is
 * gone or otherwise invalid).
 */
isPrunable: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
