[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.coverage-tarpaulin]
description = "Run test coverage using cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "--out", "Html"]

[tasks.coverage]
description = "Run test coverage using cargo-tarpaulin"
dependencies = ["coverage-tarpaulin"]

[tasks.coverage-open]
description = "Run test coverage and open the report in browser"
dependencies = ["coverage-tarpaulin"]
script = '''
#!/usr/bin/env bash
if [ -f "tarpaulin-report.html" ]; then
  echo "Opening coverage report..."
  
  # Check the operating system and use the appropriate command
  if [ "$(uname)" == "Darwin" ]; then
    open tarpaulin-report.html
  elif [ "$(uname)" == "Linux" ]; then
    xdg-open tarpaulin-report.html
  elif [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
    start tarpaulin-report.html
  else
    echo "Coverage report generated at: $(pwd)/tarpaulin-report.html"
  fi
fi
'''

[tasks.coverage-fail]
description = "Run test coverage with fail-under option"
command = "cargo"
args = ["tarpaulin", "--out", "Html", "--fail-under", "50"]

[tasks.coverage-verbose]
description = "Run test coverage with verbose output"
command = "cargo"
args = ["tarpaulin", "--verbose", "--line"]

[tasks.coverage-detailed]
description = "Run test coverage with detailed line-by-line output"
command = "cargo"
args = ["tarpaulin", "--verbose", "--line", "--output-dir", "target/tarpaulin", "--count", "--ignored"] 