
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Gets the root path of a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the path to check
 * 
 * # Returns
 * 
 * * `Result<GetRepositoryRootOutput, AppError>` - The root path and ID, or an error
 */
async getRepositoryRoot(input: GetRepositoryRootInput) : Promise<Result<GetRepositoryRootOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository_root", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new repository entry in the database.
 * This should only be called when a user explicitly adds a repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the repository path
 * * `db` - Database state for persisting repository data
 * 
 * # Returns
 * 
 * * `Result<CreateRepositoryOutput, AppError>` - Repository information or an error
 */
async createRepository(input: CreateRepositoryInput) : Promise<Result<CreateRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets information about a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing the repository path
 * * `db` - Database state for persisting repository data
 * 
 * # Returns
 * 
 * * `Result<GetRepositoryOutput, AppError>` - Repository information or an error
 */
async getRepository(input: GetRepositoryInput) : Promise<Result<GetRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all repositories from the database.
 * 
 * # Arguments
 * 
 * * `db` - Database state for retrieving repositories
 * 
 * # Returns
 * 
 * * `Result<Vec<crate::db::models::Repository>, AppError>` - List of repositories or an error
 */
async getRepositoryList() : Promise<Result<Repository[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repository_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a repository from the database.
 * 
 * # Arguments
 * 
 * * `db` - Database state for repository deletion
 * * `input` - Input parameters containing the repository ID
 * 
 * # Returns
 * 
 * * `Result<DeleteRepositoryOutput, AppError>` - Success status or an error
 */
async deleteRepository(input: DeleteRepositoryInput) : Promise<Result<DeleteRepositoryOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_repository", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists branches from the database for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repo_id and include_deleted flag
 * 
 * # Returns
 * 
 * * `Result<ListBranchesOutput, AppError>` - The list of branches or an error
 */
async listBranches(input: ListBranchesInput) : Promise<Result<ListBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the current branch in a git repository (switches to another branch).
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and branch name
 * 
 * # Returns
 * 
 * * `Result<UpdateCurrentBranchOutput, AppError>` - The new current branch name or an error
 */
async updateCurrentBranch(input: UpdateCurrentBranchInput) : Promise<Result<UpdateCurrentBranchOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_current_branch", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple branches from a git repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state for soft-deleting branches
 * * `input` - Input parameters containing path and branch names to delete
 * 
 * # Returns
 * 
 * * `Result<BatchDeleteBranchesOutput, AppError>` - The deleted branches or an error
 */
async batchDeleteBranches(input: BatchDeleteBranchesInput) : Promise<Result<BatchDeleteBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gets the reachability status of a commit SHA in a git repository.
 * 
 * # Arguments
 * 
 * * `input` - Input parameters containing path and commit SHA
 * 
 * # Returns
 * 
 * * `Result<GetCommitReachabilityOutput, AppError>` - The reachability status or an error
 */
async getCommitReachability(input: GetCommitReachabilityInput) : Promise<Result<GetCommitReachabilityOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_reachability", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a restoration of a deleted branch in a git repository.
 * 
 * # Arguments
 * 
 * * `app` - The AppHandle
 * * `db` - Database state for updating branch status
 * * `input` - Input parameters containing path and branch info
 * 
 * # Returns
 * 
 * * `Result<CreateBranchRestorationOutput, AppError>` - The restoration result or an error
 */
async createBranchRestoration(input: CreateBranchRestorationInput) : Promise<Result<CreateBranchRestorationOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch_restoration", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates restorations of multiple deleted branches in a git repository.
 * 
 * # Arguments
 * 
 * * `app` - The AppHandle
 * * `db` - Database state for updating branch status
 * * `input` - Input parameters containing path and branch infos
 * 
 * # Returns
 * 
 * * `Result<BatchCreateBranchRestorationsOutput, AppError>` - The restoration results or an error
 */
async batchCreateBranchRestorations(input: BatchCreateBranchRestorationsInput) : Promise<Result<BatchCreateBranchRestorationsOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_create_branch_restorations", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all selected branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<ListSelectedBranchesOutput, AppError>` - The selected branches or an error
 */
async listSelectedBranches(input: ListSelectedBranchesInput) : Promise<Result<ListSelectedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_selected_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates multiple selected branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchCreateSelectedBranchesOutput, AppError>` - Success or an error
 */
async batchCreateSelectedBranches(input: BatchCreateSelectedBranchesInput) : Promise<Result<BatchCreateSelectedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_create_selected_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple selected branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchDeleteSelectedBranchesOutput, AppError>` - Success or an error
 */
async batchDeleteSelectedBranches(input: BatchDeleteSelectedBranchesInput) : Promise<Result<BatchDeleteSelectedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_selected_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes all selected branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<DeleteAllSelectedBranchesOutput, AppError>` - Success or an error
 */
async deleteAllSelectedBranches(input: DeleteAllSelectedBranchesInput) : Promise<Result<DeleteAllSelectedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_all_selected_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists all locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<ListLockedBranchesOutput, AppError>` - The locked branches or an error
 */
async listLockedBranches(input: ListLockedBranchesInput) : Promise<Result<ListLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates multiple locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchCreateLockedBranchesOutput, AppError>` - Success or an error
 */
async batchCreateLockedBranches(input: BatchCreateLockedBranchesInput) : Promise<Result<BatchCreateLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_create_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes multiple locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID and branch names
 * 
 * # Returns
 * 
 * * `Result<BatchDeleteLockedBranchesOutput, AppError>` - Success or an error
 */
async batchDeleteLockedBranches(input: BatchDeleteLockedBranchesInput) : Promise<Result<BatchDeleteLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_delete_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes all locked branches for a repository.
 * 
 * # Arguments
 * 
 * * `db` - Database state
 * * `input` - Input parameters containing repository ID
 * 
 * # Returns
 * 
 * * `Result<DeleteAllLockedBranchesOutput, AppError>` - Success or an error
 */
async deleteAllLockedBranches(input: DeleteAllLockedBranchesInput) : Promise<Result<DeleteAllLockedBranchesOutput, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_all_locked_branches", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
branchDeleted: BranchDeletedEvent,
branchRestored: BranchRestoredEvent,
branchSwitched: BranchSwitchedEvent,
notification: NotificationEvent,
repositoryLoaded: RepositoryLoadedEvent
}>({
branchDeleted: "branch-deleted",
branchRestored: "branch-restored",
branchSwitched: "branch-switched",
notification: "notification",
repositoryLoaded: "repository-loaded"
})

/** user-defined constants **/



/** user-defined types **/

export type AppError = { message: string; kind: string; description: string | null }
export type BatchCreateBranchRestorationsInput = { path: string; repoId: string; branchInfos: DeletedBranch[] }
export type BatchCreateBranchRestorationsOutput = { results: RestoreBranchResult[] }
export type BatchCreateLockedBranchesInput = { repoId: string; branchNames: string[] }
export type BatchCreateLockedBranchesOutput = Record<string, never>
export type BatchCreateSelectedBranchesInput = { repoId: string; branchNames: string[]; branchContext: string }
export type BatchCreateSelectedBranchesOutput = Record<string, never>
export type BatchDeleteBranchesInput = { path: string; repoId: string; branches: string[] }
export type BatchDeleteBranchesOutput = { deletedBranches: DeletedBranchInfo[] }
export type BatchDeleteLockedBranchesInput = { repoId: string; branchNames: string[] }
export type BatchDeleteLockedBranchesOutput = Record<string, never>
export type BatchDeleteSelectedBranchesInput = { repoId: string; branchNames: string[]; branchContext: string }
export type BatchDeleteSelectedBranchesOutput = Record<string, never>
export type Branch = { name: string; fullyMerged: boolean; lastCommit: Commit; current: boolean; deletedAt: string | null; isReachable: boolean | null; isSelected: boolean; isLocked: boolean }
export type BranchDeletedEvent = { deletedBranches: DeletedBranchInfo[]; repositoryPath: string }
export type BranchRestoredEvent = { restoredBranch: Branch; repositoryPath: string }
export type BranchSwitchedEvent = { fromBranch: string; toBranch: string; repositoryPath: string }
export type Commit = { sha: string; shortSha: string; date: string; message: string; author: string; email: string }
export type ConflictDetails = { originalName: string; conflictingName: string }
export type ConflictResolution = "Overwrite" | "Rename" | "Skip"
export type CreateBranchRestorationInput = { path: string; repoId: string; branchInfo: DeletedBranch }
export type CreateBranchRestorationOutput = { result: RestoreBranchResult }
export type CreateRepositoryInput = { path: string }
export type CreateRepositoryOutput = { path: string; branches: Branch[]; currentBranch: string; branchesCount: number; name: string; id: string }
export type DeleteAllLockedBranchesInput = { repoId: string }
export type DeleteAllLockedBranchesOutput = Record<string, never>
export type DeleteAllSelectedBranchesInput = { repoId: string; branchContext: string }
export type DeleteAllSelectedBranchesOutput = Record<string, never>
export type DeleteRepositoryInput = { id: string }
export type DeleteRepositoryOutput = { success: boolean }
export type DeletedBranch = { originalName: string; targetName: string; commitSha: string; conflictResolution: ConflictResolution | null }
export type DeletedBranchInfo = { branch: Branch; rawOutput: string }
export type GetCommitReachabilityInput = { path: string; commitSha: string }
export type GetCommitReachabilityOutput = { isReachable: boolean }
export type GetRepositoryInput = { path: string }
export type GetRepositoryOutput = { path: string; branches: Branch[]; currentBranch: string; branchesCount: number; name: string; id: string }
export type GetRepositoryRootInput = { path: string }
export type GetRepositoryRootOutput = { rootPath: string; id: string | null }
export type ListBranchesInput = { repoId: string; includeDeleted: boolean }
export type ListBranchesOutput = { branches: Branch[] }
export type ListLockedBranchesInput = { repoId: string }
export type ListLockedBranchesOutput = { branches: string[] }
export type ListSelectedBranchesInput = { repoId: string; branchContext: string }
export type ListSelectedBranchesOutput = { branches: string[] }
export type NotificationEvent = { title: string; message: string; kind: NotificationKind; duration: number | null }
export type NotificationKind = "Success" | "Error" | "Warning" | "Info"
export type Repository = { id: string; name: string; path: string; currentBranch: string; branchesCount: number; createdAt: string; updatedAt: string; lastSyncHash: string | null; lastSyncTimestamp: number | null }
export type RepositoryLoadedEvent = { repositoryPath: string; repositoryName: string; branchesCount: number }
export type RestoreBranchResult = { success: boolean; branchName: string; message: string; requiresUserAction: boolean; conflictDetails: ConflictDetails | null; skipped: boolean; branch: Branch | null }
export type UpdateCurrentBranchInput = { path: string; branch: string }
export type UpdateCurrentBranchOutput = { currentBranch: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
