import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { defineConfig } from '@pandacss/dev';
import { pandaBuildInfoPath } from '@pindoba/panda-buildinfo';

// The Panda CLI runs as a standalone Node process and does not auto-load `.env`
// the way Vite does. Read it ourselves so `USE_LOCAL_PINDOBA=true` in `.env`
// affects both the JS aliases (vite.config.js) and the Panda include list.
function readDotenv(file: string): Record<string, string> {
	try {
		const out: Record<string, string> = {};
		for (const line of readFileSync(file, 'utf8').split('\n')) {
			const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
			if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '');
		}
		return out;
	} catch {
		return {};
	}
}

const dotenv = readDotenv(path.resolve(process.cwd(), '.env'));
const useLocalPindoba = (process.env.USE_LOCAL_PINDOBA ?? dotenv.USE_LOCAL_PINDOBA) === 'true';

// Recipe, token, and affix CSS is generated by the Panda CLI from
// `@pindoba/panda-preset`. Unlike the runtime `@pindoba/svelte-*` packages
// (redirected by Vite `resolve.alias`), the Panda CLI is a plain Node process
// that ignores Vite aliases — so editing the sibling preset checkout has no
// effect unless we point Panda at it here. In local mode, load the preset from
// the sibling's built `dist/` when it exists; otherwise fall back to the npm
// package so CI / release (where `../pindoba` is absent) keeps working. This is
// the Panda-side counterpart to the `USE_LOCAL_PINDOBA` Vite aliasing, and is
// safe to commit because it self-disables without the sibling checkout.
//
// The config is bundled to CommonJS by Panda (bundle-n-require), so top-level
// `await` is unavailable. Instead we hand Panda a Promise as a preset entry:
// `getResolvedConfig` does `await subPreset` for every entry, so a preset that
// resolves asynchronously via dynamic `import()` is fully supported.
const localPresetEntry = path.resolve(
	process.cwd(),
	'../pindoba/packages/panda-preset/dist/index.js'
);
const presetSpecifier =
	useLocalPindoba && existsSync(localPresetEntry)
		? pathToFileURL(localPresetEntry).href
		: '@pindoba/panda-preset';
const pindobaPreset = import(presetSpecifier).then(({ preset }) => preset());

export default defineConfig({
	// Whether to use css reset
	preflight: true,

	// Where to look for your css declarations
	include: [
		'./src/**/*.{ts,tsx,svelte}',
		// Only reference the sibling checkout's buildinfo in local mode; in CI /
		// release the `../pindoba` sibling does not exist.
		// (The @pindoba/devtools panel is deliberately NOT included here: it ships
		// its own precompiled `@pindoba/devtools/styles.css`, imported dev-only in
		// app-shell.svelte, so its CSS never gets compiled into ours.)
		...(useLocalPindoba ? ['../pindoba/packages/panda-buildinfo/dist/panda.buildinfo.json'] : []),
		pandaBuildInfoPath
	],
	exclude: [''],
	dependencies: ['@pindoba/styled-system'],
	importMap: '@pindoba/styled-system',
	watch: true,
	clean: false,
	globalCss: {
		'*': {
			overscrollBehavior: 'none'
		},
		'body, html': {
			_dark: {
				filter: 'saturate(85%)'
			}
		},
		// Polished, thin scrollbar applied globally. The Pindoba preset ships its
		// own `::-webkit-scrollbar` rules in @layer base at the same specificity;
		// prefixing with `html`/`html *` raises specificity so these win the
		// cascade (and covers both the root element and every descendant). We
		// deliberately do NOT set `scrollbar-width`, because in WebKit/Blink that
		// disables the ::-webkit-scrollbar pseudo styling below. Each property the
		// preset sets is overridden here so nothing bleeds through.
		'html::-webkit-scrollbar, html *::-webkit-scrollbar': {
			width: '8px',
			height: '8px'
		},
		'html::-webkit-scrollbar-track, html *::-webkit-scrollbar-track': {
			background: 'transparent',
			border: 'none'
		},
		'html::-webkit-scrollbar-thumb, html *::-webkit-scrollbar-thumb': {
			backgroundColor: '{colors.neutral.border.bold}',
			borderRadius: '9999px',
			border: '2px solid transparent',
			minHeight: 'auto',
			minWidth: 'auto',
			backgroundClip: 'padding-box'
		},
		'html::-webkit-scrollbar-thumb:hover, html *::-webkit-scrollbar-thumb:hover': {
			backgroundColor: '{colors.neutral.border.accent}'
		},
		'html::-webkit-scrollbar-thumb:active, html *::-webkit-scrollbar-thumb:active': {
			backgroundColor: '{colors.primary.text}'
		},
		'html::-webkit-scrollbar-corner, html *::-webkit-scrollbar-corner': {
			background: 'transparent'
		}
	},

	// Useful for theme customization
	theme: {
		extend: {
			// tokens: {
			// 	colors: {
			// 		...getRadixColorsTokens({
			// 			colorName: 'grass',
			// 			light: grass,
			// 			dark: grassDark,
			// 			lightAlpha: grassA,
			// 			darkAlpha: grassDarkA
			// 		}),
			// 		...getRadixColorsTokens({
			// 			colorName: 'olive',
			// 			light: olive,
			// 			dark: oliveDark,
			// 			lightAlpha: oliveA,
			// 			darkAlpha: oliveDarkA
			// 		})
			// 	}
			// },
			semanticTokens: {
				colors: {
					contrast: {
						value: {
							base: `#fff`,
							_light: `#000`
						}
					},
					// Commit-graph lane palette (base = dark theme, _light overrides).
					// Consumed as CSS vars by the history graph rail so SVG strokes
					// follow the theme without re-rendering.
					// Softened palette: OKLCH C ≈ 0.11 (the old Tailwind 400s sat at
					// ~0.15–0.19), with lightness alternating between adjacent lanes
					// so neighbours stay apart under color-vision deficiency. Both
					// modes pass the palette validator: lightness band, chroma floor,
					// CVD ΔE, normal-vision ΔE, and ≥3:1 contrast vs the surface.
					graph: {
						lane: {
							'0': { value: { base: '#6295d4', _light: '#4b7cba' } },
							'1': { value: { base: '#348757', _light: '#156f41' } },
							'2': { value: { base: '#af923c', _light: '#a68931' } },
							'3': { value: { base: '#a85550', _light: '#984742' } },
							'4': { value: { base: '#9489d4', _light: '#857ac4' } },
							'5': { value: { base: '#a35475', _light: '#8c4061' } },
							'6': { value: { base: '#20a89b', _light: '#009589' } },
							'7': { value: { base: '#a6662b', _light: '#965719' } }
						},
						muted: { value: { base: '#6b7280', _light: '#9ca3af' } }
					}
					// ...getSemanticTokens('primary', 'grass'),
					// ...getSemanticTokens('neutral', 'olive')
				}
			},
			keyframes: {
				// Onboarding animations
				float: {
					'0%, 100%': { transform: 'translateY(0px)' },
					'50%': { transform: 'translateY(-20px)' }
				},
				pulse: {
					'0%, 100%': { opacity: '1', transform: 'scale(1)' },
					'50%': { opacity: '0.8', transform: 'scale(1.05)' }
				},
				bellRing: {
					'0%, 100%': { transform: 'rotate(0deg)' },
					'15%': { transform: 'rotate(14deg)' },
					'30%': { transform: 'rotate(-12deg)' },
					'45%': { transform: 'rotate(10deg)' },
					'60%': { transform: 'rotate(-8deg)' },
					'75%': { transform: 'rotate(4deg)' }
				},
				fadeIn: {
					from: { opacity: '0', transform: 'translateY(20px)' },
					to: { opacity: '1', transform: 'translateY(0)' }
				},
				fadeInUp: {
					from: { opacity: '0', transform: 'translateY(15px)' },
					to: { opacity: '1', transform: 'translateY(0)' }
				},
				gradientShift: {
					'0%': { backgroundPosition: '0% 50%' },
					'50%': { backgroundPosition: '100% 50%' },
					'100%': { backgroundPosition: '0% 50%' }
				},
				slideUp: {
					from: { opacity: '0', transform: 'translateY(40px)' },
					to: { opacity: '1', transform: 'translateY(0)' }
				},
				float1: {
					'0%, 100%': { transform: 'translate(0, 0) rotate(0deg)' },
					'25%': { transform: 'translate(50px, -50px) rotate(90deg)' },
					'50%': { transform: 'translate(100px, 0) rotate(180deg)' },
					'75%': { transform: 'translate(50px, 50px) rotate(270deg)' }
				},
				float2: {
					'0%, 100%': { transform: 'translate(0, 0) scale(1)' },
					'33%': { transform: 'translate(-80px, -40px) scale(1.1)' },
					'66%': { transform: 'translate(-40px, 60px) scale(0.9)' }
				},
				float3: {
					'0%, 100%': { transform: 'translate(0, 0)' },
					'50%': { transform: 'translate(-60px, -80px)' }
				},
				rotateAngle: {
					'0%': { '--angle': '0deg' },
					'100%': { '--angle': '360deg' }
				}
			}
		}
	},

	presets: ['@pandacss/dev/presets', pindobaPreset],
	jsxFramework: 'svelte',

	// The output directory for your css system
	outdir: 'styled-system'
});
