import { render, fireEvent } from '@testing-library/svelte';
import { vi, describe, expect, test, beforeEach } from 'vitest';
import { notifications, Notification as NotificationModel } from '../../store/notifications.svelte';
import Notification from '../notification.svelte';

// Mock the debounce function to execute immediately
vi.mock('$utils/svelte-runes-utils', () => ({
	debounce: vi.fn((fn) => fn)
}));

// Mock notifications store
vi.mock('../../store/notifications.svelte', () => ({
	notifications: {
		delete: vi.fn()
	},
	Notification: class MockNotification {
		id: string;
		message: string;
		title: string;
		feedback: 'success' | 'danger' | 'warning' | 'default';
		date: number | null;

		constructor(
			id: string,
			message: string,
			title: string,
			feedback: 'success' | 'danger' | 'warning' | 'default',
			date: number | null
		) {
			this.id = id;
			this.message = message;
			this.title = title;
			this.feedback = feedback;
			this.date = date;
		}

		static create(data: {
			id?: string;
			message?: string;
			title?: string;
			feedback?: 'success' | 'danger' | 'warning' | 'default';
			date?: number | null;
		}) {
			return new MockNotification(
				data.id || crypto.randomUUID(),
				data.message || '',
				data.title || '',
				data.feedback || 'default',
				// Match the real implementation: null stays null, undefined becomes Date.now()
				data.date === null ? null : data.date === undefined ? Date.now() : data.date
			);
		}
	}
}));

describe('Notification Component', () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	test('renders with title', () => {
		const notification = NotificationModel.create({
			title: 'Test Title',
			message: 'Test Message',
			feedback: 'success'
		});

		const { getByText } = render(Notification, {
			props: {
				notification
			}
		});

		expect(getByText('Test Title')).toBeInTheDocument();
	});

	test('renders with message', () => {
		const notification = NotificationModel.create({
			message: 'Test Message',
			feedback: 'success'
		});

		const { getByText } = render(Notification, {
			props: {
				notification
			}
		});

		expect(getByText('Test Message')).toBeInTheDocument();
	});

	test('renders with feedback', () => {
		const notification = NotificationModel.create({
			message: 'Test Message',
			feedback: 'success'
		});

		const { container } = render(Notification, {
			props: {
				notification
			}
		});

		// Look for an Alert element that would contain the feedback class
		const alertElement = container.querySelector('div');
		expect(alertElement).toHaveClass('color-palette_success');
	});

	test('renders date when provided', () => {
		const testDate = Date.now();
		const notification = NotificationModel.create({
			message: 'Test Message',
			feedback: 'success',
			date: testDate
		});

		const { container } = render(Notification, {
			props: {
				notification
			}
		});

		const timeElement = container.querySelector('time');
		expect(timeElement).toBeInTheDocument();

		const alertElement = container.querySelector('div');
		expect(alertElement).toHaveClass('color-palette_success');
	});

	test('does not render date when not provided', () => {
		const notification = NotificationModel.create({
			message: 'Test Message',
			feedback: 'success',
			date: null // Explicitly set to null to omit date
		});

		const { container } = render(Notification, {
			props: {
				notification
			}
		});

		const timeElement = container.querySelector('time');
		expect(timeElement).not.toBeInTheDocument();
	});

	test('calls notifications.delete when close button is clicked', async () => {
		const notification = NotificationModel.create({
			id: '123',
			message: 'Test Message',
			feedback: 'success'
		});

		const { container } = render(Notification, {
			props: {
				notification
			}
		});

		// Find the close button
		const closeButton = container.querySelector('button');
		expect(closeButton).toBeInTheDocument();

		// Click the close button
		if (closeButton) {
			await fireEvent.click(closeButton);
		}

		// Check if notifications.delete was called with the correct ID
		expect(notifications.delete).toHaveBeenCalledWith(['123']);
	});

	test('always renders close button since all notifications have valid IDs', () => {
		const notification = NotificationModel.create({
			message: 'Test Message',
			feedback: 'success'
			// ID is auto-generated by the Value Object
		});

		const { container } = render(Notification, {
			props: {
				notification
			}
		});

		// With robust Value Objects, all notifications have IDs and are dismissible
		const closeButton = container.querySelector('button');
		expect(closeButton).toBeInTheDocument();
	});
});
