name: 'Rust Setup'
description: 'Setup Rust environment'

runs:
  using: 'composite'
  steps:
    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
