name: 'Node Setup'
description: 'Setup Node.js environment'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'

    - name: Enable corepack
      run: corepack enable
      shell: bash

    - name: Get pnpm store directory
      id: pnpm-cache-dir
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      name: Setup pnpm store cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - uses: actions/cache@v4
      name: Cache node_modules
      with:
        path: |
          **/node_modules
          !**/node_modules/.cache
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
