name: 'Node Setup'
description: 'Setup Node.js environment'

runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      shell: bash
      with:
        node-version: 'lts/*'

    - run: corepack enable
      shell: bash

    - name: Get pnpm store directory
      id: pnpm-cache-dir
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      shell: bash
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      run: pnpm install
      shell: bash
