name: 'node-setup'

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  setup:
    runs-on: ${{ inputs.platform }}
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache-dir
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install
