name: Rust check

on:
  push:
    branches:
      - '**' # Run on pushes to all branches
    tags-ignore:
      - '**' # Ignore all tags
  workflow_call:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgobject-2.0-dev

      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          platform: ubuntu-latest
          cache_key_discriminator: fmt

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        working-directory: src-tauri
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgdk-pixbuf2.0-dev libglib2.0-dev libgobject-2.0-dev

      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          platform: ubuntu-latest
          cache_key_discriminator: clippy

      - name: Install clippy
        run: rustup component add clippy

      - name: Clippy
        working-directory: src-tauri
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GTK dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgdk-pixbuf2.0-dev libglib2.0-dev libgobject-2.0-dev

      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          platform: ubuntu-latest
          cache_key_discriminator: test

      - name: Run tests
        working-directory: src-tauri
        run: cargo test --all-features
