name: 'Svelte check'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

concurrency:
  group: svelte-check-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: node-setup
        uses: ./.github/actions/node-setup

      - name: Check formatting
        run: pnpm format

  svelte-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: node-setup
        uses: ./.github/actions/node-setup

      - name: Run Svelte check
        run: pnpm check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: node-setup
        uses: ./.github/actions/node-setup

      - name: Run ESLint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: node-setup
        uses: ./.github/actions/node-setup
        with:
          playwright: 'true'

      - name: Run Tests
        run: pnpm test
