name: 'test'

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: node-setup
        uses: ./.github/actions/node-setup

      - name: Run Tests
        run: pnpm test
